services:
  - type: web
    name: mariadb-ai-api
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_HOST
        value: your-mariadb-host
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: your-db-user
      - key: DB_PASS
        value: your-db-password
      - key: DB_NAME
        value: your-db-name
